{% set name = "sparseconverter" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sparseconverter-{{ version }}.tar.gz
  sha256: b152a31cc16ef85a7a08c9e4c0ae1957f9e5ad94914feef13d529b02c4c1b0bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - sparse >=0.12
    - typing-extensions

test:
  imports:
    - sparseconverter
  commands:
    - pip check
    - pytest --durations=10 --cov=sparseconverter --cov-report=term --cov-config=setup.cfg tests/
  requires:
    - pip
    - pytest
    - pytest-cov
  source_files:
    - tests
#    - pytest.ini  - not yet included in sdist - uncomment once that's changed
    - setup.cfg

about:
  home: https://github.com/LiberTEM/sparseconverter
  summary: Sparse array type conversion utility
  license: MIT
  license_file: LICENSE
  description: |
    Converter matrix and type determination for
    a range of array formats, focusing on sparse arrays

extra:
  recipe-maintainers:
    - sk1p
    - uellue
    - matbryan52
